// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: catalog/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReq) Reset() {
	*x = GetProductsReq{}
	mi := &file_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReq) ProtoMessage() {}

func (x *GetProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReq.ProtoReflect.Descriptor instead.
func (*GetProductsReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceMinor    int64                  `protobuf:"varint,4,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRes) Reset() {
	*x = ProductRes{}
	mi := &file_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRes) ProtoMessage() {}

func (x *ProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRes.ProtoReflect.Descriptor instead.
func (*ProductRes) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ProductRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductRes) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *ProductRes) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductRes) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProductRes) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetProductsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductRes          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRes) Reset() {
	*x = GetProductsRes{}
	mi := &file_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRes) ProtoMessage() {}

func (x *GetProductsRes) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRes.ProtoReflect.Descriptor instead.
func (*GetProductsRes) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsRes) GetProducts() []*ProductRes {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_catalog_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductRes          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRes) Reset() {
	*x = ListProductsRes{}
	mi := &file_catalog_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRes) ProtoMessage() {}

func (x *ListProductsRes) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRes.ProtoReflect.Descriptor instead.
func (*ListProductsRes) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsRes) GetProducts() []*ProductRes {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceMinor    int64                  `protobuf:"varint,3,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Active        bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_catalog_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *CreateProductReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductReq) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateProductReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceMinor    int64                  `protobuf:"varint,4,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_catalog_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *UpdateProductReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateProductReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateProductReq) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UpdateProductReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_catalog_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRes) Reset() {
	*x = DeleteProductRes{}
	mi := &file_catalog_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRes) ProtoMessage() {}

func (x *DeleteProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRes.ProtoReflect.Descriptor instead.
func (*DeleteProductRes) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRes) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ResetDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetDataReq) Reset() {
	*x = ResetDataReq{}
	mi := &file_catalog_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetDataReq) ProtoMessage() {}

func (x *ResetDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetDataReq.ProtoReflect.Descriptor instead.
func (*ResetDataReq) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{10}
}

type ResetDataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetDataRes) Reset() {
	*x = ResetDataRes{}
	mi := &file_catalog_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetDataRes) ProtoMessage() {}

func (x *ResetDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetDataRes.ProtoReflect.Descriptor instead.
func (*ResetDataRes) Descriptor() ([]byte, []int) {
	return file_catalog_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ResetDataRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_catalog_catalog_proto protoreflect.FileDescriptor

const file_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x15catalog/catalog.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x0eGetProductsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xfc\x01\n" +
	"\n" +
	"ProductRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_minor\x18\x04 \x01(\x03R\n" +
	"priceMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x127\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"9\n" +
	"\x0eGetProductsRes\x12'\n" +
	"\bproducts\x18\x01 \x03(\v2\v.ProductResR\bproducts\"B\n" +
	"\x0fListProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"P\n" +
	"\x0fListProductsRes\x12'\n" +
	"\bproducts\x18\x01 \x03(\v2\v.ProductResR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf2\x01\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_minor\x18\x03 \x01(\x03R\n" +
	"priceMinor\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\"\x82\x02\n" +
	"\x10UpdateProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_minor\x18\x04 \x01(\x03R\n" +
	"priceMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x127\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"\"\n" +
	"\x10DeleteProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x10DeleteProductRes\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x0e\n" +
	"\fResetDataReq\"$\n" +
	"\fResetDataRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xdd\x02\n" +
	"\aCatalog\x12)\n" +
	"\n" +
	"GetProduct\x12\x0e.GetProductReq\x1a\v.ProductRes\x12/\n" +
	"\vGetProducts\x12\x0f.GetProductsReq\x1a\x0f.GetProductsRes\x122\n" +
	"\fListProducts\x12\x10.ListProductsReq\x1a\x10.ListProductsRes\x12/\n" +
	"\rCreateProduct\x12\x11.CreateProductReq\x1a\v.ProductRes\x12/\n" +
	"\rUpdateProduct\x12\x11.UpdateProductReq\x1a\v.ProductRes\x125\n" +
	"\rDeleteProduct\x12\x11.DeleteProductReq\x1a\x11.DeleteProductRes\x12)\n" +
	"\tResetData\x12\r.ResetDataReq\x1a\r.ResetDataResB\x19Z\x17proto/catalog;catalogpbb\x06proto3"

var (
	file_catalog_catalog_proto_rawDescOnce sync.Once
	file_catalog_catalog_proto_rawDescData []byte
)

func file_catalog_catalog_proto_rawDescGZIP() []byte {
	file_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_catalog_proto_rawDesc), len(file_catalog_catalog_proto_rawDesc)))
	})
	return file_catalog_catalog_proto_rawDescData
}

var file_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_catalog_catalog_proto_goTypes = []any{
	(*GetProductReq)(nil),    // 0: GetProductReq
	(*GetProductsReq)(nil),   // 1: GetProductsReq
	(*ProductRes)(nil),       // 2: ProductRes
	(*GetProductsRes)(nil),   // 3: GetProductsRes
	(*ListProductsReq)(nil),  // 4: ListProductsReq
	(*ListProductsRes)(nil),  // 5: ListProductsRes
	(*CreateProductReq)(nil), // 6: CreateProductReq
	(*UpdateProductReq)(nil), // 7: UpdateProductReq
	(*DeleteProductReq)(nil), // 8: DeleteProductReq
	(*DeleteProductRes)(nil), // 9: DeleteProductRes
	(*ResetDataReq)(nil),     // 10: ResetDataReq
	(*ResetDataRes)(nil),     // 11: ResetDataRes
	(*structpb.Struct)(nil),  // 12: google.protobuf.Struct
}
var file_catalog_catalog_proto_depIdxs = []int32{
	12, // 0: ProductRes.attributes:type_name -> google.protobuf.Struct
	2,  // 1: GetProductsRes.products:type_name -> ProductRes
	2,  // 2: ListProductsRes.products:type_name -> ProductRes
	12, // 3: CreateProductReq.attributes:type_name -> google.protobuf.Struct
	12, // 4: UpdateProductReq.attributes:type_name -> google.protobuf.Struct
	0,  // 5: Catalog.GetProduct:input_type -> GetProductReq
	1,  // 6: Catalog.GetProducts:input_type -> GetProductsReq
	4,  // 7: Catalog.ListProducts:input_type -> ListProductsReq
	6,  // 8: Catalog.CreateProduct:input_type -> CreateProductReq
	7,  // 9: Catalog.UpdateProduct:input_type -> UpdateProductReq
	8,  // 10: Catalog.DeleteProduct:input_type -> DeleteProductReq
	10, // 11: Catalog.ResetData:input_type -> ResetDataReq
	2,  // 12: Catalog.GetProduct:output_type -> ProductRes
	3,  // 13: Catalog.GetProducts:output_type -> GetProductsRes
	5,  // 14: Catalog.ListProducts:output_type -> ListProductsRes
	2,  // 15: Catalog.CreateProduct:output_type -> ProductRes
	2,  // 16: Catalog.UpdateProduct:output_type -> ProductRes
	9,  // 17: Catalog.DeleteProduct:output_type -> DeleteProductRes
	11, // 18: Catalog.ResetData:output_type -> ResetDataRes
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_catalog_catalog_proto_init() }
func file_catalog_catalog_proto_init() {
	if File_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_catalog_proto_rawDesc), len(file_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_catalog_proto_msgTypes,
	}.Build()
	File_catalog_catalog_proto = out.File
	file_catalog_catalog_proto_goTypes = nil
	file_catalog_catalog_proto_depIdxs = nil
}
