// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/payments/payments.proto

package paymentspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payments_CreatePayment_FullMethodName      = "/Payments/CreatePayment"
	Payments_GetPayment_FullMethodName         = "/Payments/GetPayment"
	Payments_AdminListPayments_FullMethodName  = "/Payments/AdminListPayments"
	Payments_AdminDeletePayment_FullMethodName = "/Payments/AdminDeletePayment"
)

// PaymentsClient is the client API for Payments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentRes, error)
	GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*PaymentRes, error)
	AdminListPayments(ctx context.Context, in *AdminListPaymentsReq, opts ...grpc.CallOption) (*AdminListPaymentsRes, error)
	AdminDeletePayment(ctx context.Context, in *AdminDeletePaymentReq, opts ...grpc.CallOption) (*AdminDeletePaymentRes, error)
}

type paymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsClient(cc grpc.ClientConnInterface) PaymentsClient {
	return &paymentsClient{cc}
}

func (c *paymentsClient) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentRes)
	err := c.cc.Invoke(ctx, Payments_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*PaymentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRes)
	err := c.cc.Invoke(ctx, Payments_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) AdminListPayments(ctx context.Context, in *AdminListPaymentsReq, opts ...grpc.CallOption) (*AdminListPaymentsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPaymentsRes)
	err := c.cc.Invoke(ctx, Payments_AdminListPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) AdminDeletePayment(ctx context.Context, in *AdminDeletePaymentReq, opts ...grpc.CallOption) (*AdminDeletePaymentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeletePaymentRes)
	err := c.cc.Invoke(ctx, Payments_AdminDeletePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServer is the server API for Payments service.
// All implementations must embed UnimplementedPaymentsServer
// for forward compatibility.
type PaymentsServer interface {
	CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentRes, error)
	GetPayment(context.Context, *GetPaymentReq) (*PaymentRes, error)
	AdminListPayments(context.Context, *AdminListPaymentsReq) (*AdminListPaymentsRes, error)
	AdminDeletePayment(context.Context, *AdminDeletePaymentReq) (*AdminDeletePaymentRes, error)
	mustEmbedUnimplementedPaymentsServer()
}

// UnimplementedPaymentsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentsServer struct{}

func (UnimplementedPaymentsServer) CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentsServer) GetPayment(context.Context, *GetPaymentReq) (*PaymentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentsServer) AdminListPayments(context.Context, *AdminListPaymentsReq) (*AdminListPaymentsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListPayments not implemented")
}
func (UnimplementedPaymentsServer) AdminDeletePayment(context.Context, *AdminDeletePaymentReq) (*AdminDeletePaymentRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeletePayment not implemented")
}
func (UnimplementedPaymentsServer) mustEmbedUnimplementedPaymentsServer() {}
func (UnimplementedPaymentsServer) testEmbeddedByValue()                  {}

// UnsafePaymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServer will
// result in compilation errors.
type UnsafePaymentsServer interface {
	mustEmbedUnimplementedPaymentsServer()
}

func RegisterPaymentsServer(s grpc.ServiceRegistrar, srv PaymentsServer) {
	// If the following call panics, it indicates UnimplementedPaymentsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payments_ServiceDesc, srv)
}

func _Payments_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).CreatePayment(ctx, req.(*CreatePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).GetPayment(ctx, req.(*GetPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_AdminListPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPaymentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).AdminListPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_AdminListPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).AdminListPayments(ctx, req.(*AdminListPaymentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_AdminDeletePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeletePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).AdminDeletePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_AdminDeletePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).AdminDeletePayment(ctx, req.(*AdminDeletePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Payments_ServiceDesc is the grpc.ServiceDesc for Payments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Payments",
	HandlerType: (*PaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _Payments_CreatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _Payments_GetPayment_Handler,
		},
		{
			MethodName: "AdminListPayments",
			Handler:    _Payments_AdminListPayments_Handler,
		},
		{
			MethodName: "AdminDeletePayment",
			Handler:    _Payments_AdminDeletePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payments/payments.proto",
}
