// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/payments/payments.proto

package paymentspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CustomerEmail string                 `protobuf:"bytes,4,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentReq) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CreatePaymentReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentReq) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CreatePaymentReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePaymentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,2,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRes) Reset() {
	*x = CreatePaymentRes{}
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRes) ProtoMessage() {}

func (x *CreatePaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRes.ProtoReflect.Descriptor instead.
func (*CreatePaymentRes) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRes) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentRes) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type GetPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentReq) Reset() {
	*x = GetPaymentReq{}
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentReq) ProtoMessage() {}

func (x *GetPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentReq.ProtoReflect.Descriptor instead.
func (*GetPaymentReq) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentReq) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PaymentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,7,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        string                 `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRes) Reset() {
	*x = PaymentRes{}
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRes) ProtoMessage() {}

func (x *PaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRes.ProtoReflect.Descriptor instead.
func (*PaymentRes) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentRes) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentRes) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentRes) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *PaymentRes) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentRes) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *PaymentRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentRes) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type AdminListPaymentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsReq) Reset() {
	*x = AdminListPaymentsReq{}
	mi := &file_proto_payments_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsReq) ProtoMessage() {}

func (x *AdminListPaymentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsReq.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsReq) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{4}
}

func (x *AdminListPaymentsReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AdminListPaymentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentRes          `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsRes) Reset() {
	*x = AdminListPaymentsRes{}
	mi := &file_proto_payments_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsRes) ProtoMessage() {}

func (x *AdminListPaymentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsRes.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsRes) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{5}
}

func (x *AdminListPaymentsRes) GetPayments() []*PaymentRes {
	if x != nil {
		return x.Payments
	}
	return nil
}

type AdminDeletePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeletePaymentReq) Reset() {
	*x = AdminDeletePaymentReq{}
	mi := &file_proto_payments_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeletePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletePaymentReq) ProtoMessage() {}

func (x *AdminDeletePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletePaymentReq.ProtoReflect.Descriptor instead.
func (*AdminDeletePaymentReq) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{6}
}

func (x *AdminDeletePaymentReq) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type AdminDeletePaymentRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeletePaymentRes) Reset() {
	*x = AdminDeletePaymentRes{}
	mi := &file_proto_payments_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeletePaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletePaymentRes) ProtoMessage() {}

func (x *AdminDeletePaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletePaymentRes.ProtoReflect.Descriptor instead.
func (*AdminDeletePaymentRes) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{7}
}

func (x *AdminDeletePaymentRes) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_proto_payments_payments_proto protoreflect.FileDescriptor

const file_proto_payments_payments_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/payments/payments.proto\"\xb5\x01\n" +
	"\x10CreatePaymentReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\famount_minor\x18\x02 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0ecustomer_email\x18\x04 \x01(\tR\rcustomerEmail\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"T\n" +
	"\x10CreatePaymentRes\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\x02 \x01(\tR\vcheckoutUrl\"I\n" +
	"\rGetPaymentReq\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x85\x02\n" +
	"\n" +
	"PaymentRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\famount_minor\x18\x05 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fcheckout_url\x18\a \x01(\tR\vcheckoutUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\t \x01(\tR\x06paidAt\"1\n" +
	"\x14AdminListPaymentsReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"?\n" +
	"\x14AdminListPaymentsRes\x12'\n" +
	"\bpayments\x18\x01 \x03(\v2\v.PaymentResR\bpayments\"6\n" +
	"\x15AdminDeletePaymentReq\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"1\n" +
	"\x15AdminDeletePaymentRes\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xf5\x01\n" +
	"\bPayments\x125\n" +
	"\rCreatePayment\x12\x11.CreatePaymentReq\x1a\x11.CreatePaymentRes\x12)\n" +
	"\n" +
	"GetPayment\x12\x0e.GetPaymentReq\x1a\v.PaymentRes\x12A\n" +
	"\x11AdminListPayments\x12\x15.AdminListPaymentsReq\x1a\x15.AdminListPaymentsRes\x12D\n" +
	"\x12AdminDeletePayment\x12\x16.AdminDeletePaymentReq\x1a\x16.AdminDeletePaymentResB\x1bZ\x19proto/payments;paymentspbb\x06proto3"

var (
	file_proto_payments_payments_proto_rawDescOnce sync.Once
	file_proto_payments_payments_proto_rawDescData []byte
)

func file_proto_payments_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)))
	})
	return file_proto_payments_payments_proto_rawDescData
}

var file_proto_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_payments_payments_proto_goTypes = []any{
	(*CreatePaymentReq)(nil),      // 0: CreatePaymentReq
	(*CreatePaymentRes)(nil),      // 1: CreatePaymentRes
	(*GetPaymentReq)(nil),         // 2: GetPaymentReq
	(*PaymentRes)(nil),            // 3: PaymentRes
	(*AdminListPaymentsReq)(nil),  // 4: AdminListPaymentsReq
	(*AdminListPaymentsRes)(nil),  // 5: AdminListPaymentsRes
	(*AdminDeletePaymentReq)(nil), // 6: AdminDeletePaymentReq
	(*AdminDeletePaymentRes)(nil), // 7: AdminDeletePaymentRes
}
var file_proto_payments_payments_proto_depIdxs = []int32{
	3, // 0: AdminListPaymentsRes.payments:type_name -> PaymentRes
	0, // 1: Payments.CreatePayment:input_type -> CreatePaymentReq
	2, // 2: Payments.GetPayment:input_type -> GetPaymentReq
	4, // 3: Payments.AdminListPayments:input_type -> AdminListPaymentsReq
	6, // 4: Payments.AdminDeletePayment:input_type -> AdminDeletePaymentReq
	1, // 5: Payments.CreatePayment:output_type -> CreatePaymentRes
	3, // 6: Payments.GetPayment:output_type -> PaymentRes
	5, // 7: Payments.AdminListPayments:output_type -> AdminListPaymentsRes
	7, // 8: Payments.AdminDeletePayment:output_type -> AdminDeletePaymentRes
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_payments_payments_proto_init() }
func file_proto_payments_payments_proto_init() {
	if File_proto_payments_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payments_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_payments_proto_depIdxs,
		MessageInfos:      file_proto_payments_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_payments_proto = out.File
	file_proto_payments_payments_proto_goTypes = nil
	file_proto_payments_payments_proto_depIdxs = nil
}
