// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/order/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItemInput) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemInput) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Items         []*OrderItemInput      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOrderReq) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	SubtotalMinor int64                  `protobuf:"varint,4,opt,name=subtotal_minor,json=subtotalMinor,proto3" json:"subtotal_minor,omitempty"`
	TotalMinor    int64                  `protobuf:"varint,5,opt,name=total_minor,json=totalMinor,proto3" json:"total_minor,omitempty"`
	PaymentId     string                 `protobuf:"bytes,6,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,7,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_proto_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRes) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderRes) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRes) GetSubtotalMinor() int64 {
	if x != nil {
		return x.SubtotalMinor
	}
	return 0
}

func (x *CreateOrderRes) GetTotalMinor() int64 {
	if x != nil {
		return x.TotalMinor
	}
	return 0
}

func (x *CreateOrderRes) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateOrderRes) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_proto_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OrderItemRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceMinor int64                  `protobuf:"varint,4,opt,name=unit_price_minor,json=unitPriceMinor,proto3" json:"unit_price_minor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItemRes) Reset() {
	*x = OrderItemRes{}
	mi := &file_proto_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemRes) ProtoMessage() {}

func (x *OrderItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemRes.ProtoReflect.Descriptor instead.
func (*OrderItemRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItemRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItemRes) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemRes) GetUnitPriceMinor() int64 {
	if x != nil {
		return x.UnitPriceMinor
	}
	return 0
}

type OrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	SubtotalMinor int64                  `protobuf:"varint,5,opt,name=subtotal_minor,json=subtotalMinor,proto3" json:"subtotal_minor,omitempty"`
	TotalMinor    int64                  `protobuf:"varint,6,opt,name=total_minor,json=totalMinor,proto3" json:"total_minor,omitempty"`
	PaymentId     string                 `protobuf:"bytes,7,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,8,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	Items         []*OrderItemRes        `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        string                 `protobuf:"bytes,11,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	mi := &file_proto_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderRes) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderRes) GetSubtotalMinor() int64 {
	if x != nil {
		return x.SubtotalMinor
	}
	return 0
}

func (x *OrderRes) GetTotalMinor() int64 {
	if x != nil {
		return x.TotalMinor
	}
	return 0
}

func (x *OrderRes) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *OrderRes) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *OrderRes) GetItems() []*OrderItemRes {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderRes) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_proto_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListOrdersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderRes            `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRes) Reset() {
	*x = ListOrdersRes{}
	mi := &file_proto_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRes) ProtoMessage() {}

func (x *ListOrdersRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRes.ProtoReflect.Descriptor instead.
func (*ListOrdersRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersRes) GetOrders() []*OrderRes {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AdminListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListOrdersReq) Reset() {
	*x = AdminListOrdersReq{}
	mi := &file_proto_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListOrdersReq) ProtoMessage() {}

func (x *AdminListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListOrdersReq.ProtoReflect.Descriptor instead.
func (*AdminListOrdersReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *AdminListOrdersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AdminGetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetOrderReq) Reset() {
	*x = AdminGetOrderReq{}
	mi := &file_proto_order_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetOrderReq) ProtoMessage() {}

func (x *AdminGetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetOrderReq.ProtoReflect.Descriptor instead.
func (*AdminGetOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGetOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AdminDeleteOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteOrderReq) Reset() {
	*x = AdminDeleteOrderReq{}
	mi := &file_proto_order_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteOrderReq) ProtoMessage() {}

func (x *AdminDeleteOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteOrderReq.ProtoReflect.Descriptor instead.
func (*AdminDeleteOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{10}
}

func (x *AdminDeleteOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type AdminDeleteOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteOrderRes) Reset() {
	*x = AdminDeleteOrderRes{}
	mi := &file_proto_order_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteOrderRes) ProtoMessage() {}

func (x *AdminDeleteOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteOrderRes.ProtoReflect.Descriptor instead.
func (*AdminDeleteOrderRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{11}
}

func (x *AdminDeleteOrderRes) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AdminUpdateOrderStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateOrderStatusReq) Reset() {
	*x = AdminUpdateOrderStatusReq{}
	mi := &file_proto_order_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateOrderStatusReq) ProtoMessage() {}

func (x *AdminUpdateOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateOrderStatusReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUpdateOrderStatusReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AdminUpdateOrderStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReq) Reset() {
	*x = GetCartReq{}
	mi := &file_proto_order_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReq) ProtoMessage() {}

func (x *GetCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReq.ProtoReflect.Descriptor instead.
func (*GetCartReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{13}
}

func (x *GetCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CartItemRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceMinor int64                  `protobuf:"varint,4,opt,name=unit_price_minor,json=unitPriceMinor,proto3" json:"unit_price_minor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CartItemRes) Reset() {
	*x = CartItemRes{}
	mi := &file_proto_order_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRes) ProtoMessage() {}

func (x *CartItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRes.ProtoReflect.Descriptor instead.
func (*CartItemRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{14}
}

func (x *CartItemRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItemRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItemRes) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemRes) GetUnitPriceMinor() int64 {
	if x != nil {
		return x.UnitPriceMinor
	}
	return 0
}

type CartRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItemRes         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SubtotalMinor int64                  `protobuf:"varint,2,opt,name=subtotal_minor,json=subtotalMinor,proto3" json:"subtotal_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRes) Reset() {
	*x = CartRes{}
	mi := &file_proto_order_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRes) ProtoMessage() {}

func (x *CartRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRes.ProtoReflect.Descriptor instead.
func (*CartRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{15}
}

func (x *CartRes) GetItems() []*CartItemRes {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartRes) GetSubtotalMinor() int64 {
	if x != nil {
		return x.SubtotalMinor
	}
	return 0
}

type AddToCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartReq) Reset() {
	*x = AddToCartReq{}
	mi := &file_proto_order_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartReq) ProtoMessage() {}

func (x *AddToCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartReq.ProtoReflect.Descriptor instead.
func (*AddToCartReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{16}
}

func (x *AddToCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToCartReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddToCartReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemReq) Reset() {
	*x = UpdateCartItemReq{}
	mi := &file_proto_order_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemReq) ProtoMessage() {}

func (x *UpdateCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemReq.ProtoReflect.Descriptor instead.
func (*UpdateCartItemReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCartItemReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCartItemReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateCartItemReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ClearCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartReq) Reset() {
	*x = ClearCartReq{}
	mi := &file_proto_order_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartReq) ProtoMessage() {}

func (x *ClearCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartReq.ProtoReflect.Descriptor instead.
func (*ClearCartReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{18}
}

func (x *ClearCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       bool                   `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRes) Reset() {
	*x = ClearCartRes{}
	mi := &file_proto_order_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRes) ProtoMessage() {}

func (x *ClearCartRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRes.ProtoReflect.Descriptor instead.
func (*ClearCartRes) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{19}
}

func (x *ClearCartRes) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type CheckoutCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutCartReq) Reset() {
	*x = CheckoutCartReq{}
	mi := &file_proto_order_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutCartReq) ProtoMessage() {}

func (x *CheckoutCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutCartReq.ProtoReflect.Descriptor instead.
func (*CheckoutCartReq) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{20}
}

func (x *CheckoutCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckoutCartReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_order_order_proto protoreflect.FileDescriptor

const file_proto_order_order_proto_rawDesc = "" +
	"\n" +
	"\x17proto/order/order.proto\"K\n" +
	"\x0eOrderItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"f\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x05items\x18\x03 \x03(\v2\x0f.OrderItemInputR\x05items\"\xe9\x01\n" +
	"\x0eCreateOrderRes\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0esubtotal_minor\x18\x04 \x01(\x03R\rsubtotalMinor\x12\x1f\n" +
	"\vtotal_minor\x18\x05 \x01(\x03R\n" +
	"totalMinor\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x06 \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\a \x01(\tR\vcheckoutUrl\"A\n" +
	"\vGetOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x87\x01\n" +
	"\fOrderItemRes\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_minor\x18\x04 \x01(\x03R\x0eunitPriceMinor\"\xce\x02\n" +
	"\bOrderRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0esubtotal_minor\x18\x05 \x01(\x03R\rsubtotalMinor\x12\x1f\n" +
	"\vtotal_minor\x18\x06 \x01(\x03R\n" +
	"totalMinor\x12\x1d\n" +
	"\n" +
	"payment_id\x18\a \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\b \x01(\tR\vcheckoutUrl\x12#\n" +
	"\x05items\x18\t \x03(\v2\r.OrderItemResR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\v \x01(\tR\x06paidAt\"(\n" +
	"\rListOrdersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\rListOrdersRes\x12!\n" +
	"\x06orders\x18\x01 \x03(\v2\t.OrderResR\x06orders\"-\n" +
	"\x12AdminListOrdersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x10AdminGetOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"0\n" +
	"\x13AdminDeleteOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"/\n" +
	"\x13AdminDeleteOrderRes\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"N\n" +
	"\x19AdminUpdateOrderStatusReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"%\n" +
	"\n" +
	"GetCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x86\x01\n" +
	"\vCartItemRes\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_minor\x18\x04 \x01(\x03R\x0eunitPriceMinor\"T\n" +
	"\aCartRes\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.CartItemResR\x05items\x12%\n" +
	"\x0esubtotal_minor\x18\x02 \x01(\x03R\rsubtotalMinor\"b\n" +
	"\fAddToCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"g\n" +
	"\x11UpdateCartItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"'\n" +
	"\fClearCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"(\n" +
	"\fClearCartRes\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\"@\n" +
	"\x0fCheckoutCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\xc9\x04\n" +
	"\x05Order\x12/\n" +
	"\vCreateOrder\x12\x0f.CreateOrderReq\x1a\x0f.CreateOrderRes\x12#\n" +
	"\bGetOrder\x12\f.GetOrderReq\x1a\t.OrderRes\x12,\n" +
	"\n" +
	"ListOrders\x12\x0e.ListOrdersReq\x1a\x0e.ListOrdersRes\x126\n" +
	"\x0fAdminListOrders\x12\x13.AdminListOrdersReq\x1a\x0e.ListOrdersRes\x12-\n" +
	"\rAdminGetOrder\x12\x11.AdminGetOrderReq\x1a\t.OrderRes\x12>\n" +
	"\x10AdminDeleteOrder\x12\x14.AdminDeleteOrderReq\x1a\x14.AdminDeleteOrderRes\x12?\n" +
	"\x16AdminUpdateOrderStatus\x12\x1a.AdminUpdateOrderStatusReq\x1a\t.OrderRes\x12 \n" +
	"\aGetCart\x12\v.GetCartReq\x1a\b.CartRes\x12$\n" +
	"\tAddToCart\x12\r.AddToCartReq\x1a\b.CartRes\x12.\n" +
	"\x0eUpdateCartItem\x12\x12.UpdateCartItemReq\x1a\b.CartRes\x12)\n" +
	"\tClearCart\x12\r.ClearCartReq\x1a\r.ClearCartRes\x121\n" +
	"\fCheckoutCart\x12\x10.CheckoutCartReq\x1a\x0f.CreateOrderResB\x15Z\x13proto/order;orderpbb\x06proto3"

var (
	file_proto_order_order_proto_rawDescOnce sync.Once
	file_proto_order_order_proto_rawDescData []byte
)

func file_proto_order_order_proto_rawDescGZIP() []byte {
	file_proto_order_order_proto_rawDescOnce.Do(func() {
		file_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_order_proto_rawDesc), len(file_proto_order_order_proto_rawDesc)))
	})
	return file_proto_order_order_proto_rawDescData
}

var file_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_order_order_proto_goTypes = []any{
	(*OrderItemInput)(nil),            // 0: OrderItemInput
	(*CreateOrderReq)(nil),            // 1: CreateOrderReq
	(*CreateOrderRes)(nil),            // 2: CreateOrderRes
	(*GetOrderReq)(nil),               // 3: GetOrderReq
	(*OrderItemRes)(nil),              // 4: OrderItemRes
	(*OrderRes)(nil),                  // 5: OrderRes
	(*ListOrdersReq)(nil),             // 6: ListOrdersReq
	(*ListOrdersRes)(nil),             // 7: ListOrdersRes
	(*AdminListOrdersReq)(nil),        // 8: AdminListOrdersReq
	(*AdminGetOrderReq)(nil),          // 9: AdminGetOrderReq
	(*AdminDeleteOrderReq)(nil),       // 10: AdminDeleteOrderReq
	(*AdminDeleteOrderRes)(nil),       // 11: AdminDeleteOrderRes
	(*AdminUpdateOrderStatusReq)(nil), // 12: AdminUpdateOrderStatusReq
	(*GetCartReq)(nil),                // 13: GetCartReq
	(*CartItemRes)(nil),               // 14: CartItemRes
	(*CartRes)(nil),                   // 15: CartRes
	(*AddToCartReq)(nil),              // 16: AddToCartReq
	(*UpdateCartItemReq)(nil),         // 17: UpdateCartItemReq
	(*ClearCartReq)(nil),              // 18: ClearCartReq
	(*ClearCartRes)(nil),              // 19: ClearCartRes
	(*CheckoutCartReq)(nil),           // 20: CheckoutCartReq
}
var file_proto_order_order_proto_depIdxs = []int32{
	0,  // 0: CreateOrderReq.items:type_name -> OrderItemInput
	4,  // 1: OrderRes.items:type_name -> OrderItemRes
	5,  // 2: ListOrdersRes.orders:type_name -> OrderRes
	14, // 3: CartRes.items:type_name -> CartItemRes
	1,  // 4: Order.CreateOrder:input_type -> CreateOrderReq
	3,  // 5: Order.GetOrder:input_type -> GetOrderReq
	6,  // 6: Order.ListOrders:input_type -> ListOrdersReq
	8,  // 7: Order.AdminListOrders:input_type -> AdminListOrdersReq
	9,  // 8: Order.AdminGetOrder:input_type -> AdminGetOrderReq
	10, // 9: Order.AdminDeleteOrder:input_type -> AdminDeleteOrderReq
	12, // 10: Order.AdminUpdateOrderStatus:input_type -> AdminUpdateOrderStatusReq
	13, // 11: Order.GetCart:input_type -> GetCartReq
	16, // 12: Order.AddToCart:input_type -> AddToCartReq
	17, // 13: Order.UpdateCartItem:input_type -> UpdateCartItemReq
	18, // 14: Order.ClearCart:input_type -> ClearCartReq
	20, // 15: Order.CheckoutCart:input_type -> CheckoutCartReq
	2,  // 16: Order.CreateOrder:output_type -> CreateOrderRes
	5,  // 17: Order.GetOrder:output_type -> OrderRes
	7,  // 18: Order.ListOrders:output_type -> ListOrdersRes
	7,  // 19: Order.AdminListOrders:output_type -> ListOrdersRes
	5,  // 20: Order.AdminGetOrder:output_type -> OrderRes
	11, // 21: Order.AdminDeleteOrder:output_type -> AdminDeleteOrderRes
	5,  // 22: Order.AdminUpdateOrderStatus:output_type -> OrderRes
	15, // 23: Order.GetCart:output_type -> CartRes
	15, // 24: Order.AddToCart:output_type -> CartRes
	15, // 25: Order.UpdateCartItem:output_type -> CartRes
	19, // 26: Order.ClearCart:output_type -> ClearCartRes
	2,  // 27: Order.CheckoutCart:output_type -> CreateOrderRes
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_order_order_proto_init() }
func file_proto_order_order_proto_init() {
	if File_proto_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_order_proto_rawDesc), len(file_proto_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_order_proto_goTypes,
		DependencyIndexes: file_proto_order_order_proto_depIdxs,
		MessageInfos:      file_proto_order_order_proto_msgTypes,
	}.Build()
	File_proto_order_order_proto = out.File
	file_proto_order_order_proto_goTypes = nil
	file_proto_order_order_proto_depIdxs = nil
}
